### ISSUE TITLE
Error in reading BRW file

### ISSUE THREAD

**Issue by tbenst** [spyking-circus/spyking-circus#55]
I saw from the release notes that BRW files are now supported so tried spyking-circus on a recording. I got the error below. Any ideas what is going wrong? This file is 170GB but I can get a smaller recording to share if helpful.

Thanks!

```
$ spyking-circus R1_E1_AMES_30min_acuity_flashes.brw  -c 12

##################################################################
#####           Welcome to the SpyKING CIRCUS (0.6.2)        #####
#####                                                        #####
#####              Written by P.Yger and O.Marre             #####
##################################################################


Steps         : filtering, whitening, clustering, fitting
GPU detected  : False
Number of CPU : 12/12
Parallel HDF5 : False
Shared memory : False   [please consider upgrading MPI]
Hostfile      : /home/tyler/spyking-circus/circus.hosts

##################################################################


-------------------------  Informations  -------------------------
| Number of recorded channels : 4096
| Number of analyzed channels : 4096
| File format                 : BRW
| Data type                   : uint16
| Sampling rate               : 17 kHz
| Duration of the recording   : 19 min 39 s 397 ms
| Width of the templates      : 5 ms
| Spatial radius considered   : 250 um
| Threshold crossing          : negative
| Waveform alignment          : True
| Matched filters             : False
| Template Extraction         : median-raw
| Overwrite                   : False
| Collect all spikes          : False
| Smart Search                : True
| Smart Selection             : False
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Large number of electrodes, reducing chunk sizes to 10s
------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tyler/lib/anaconda3/bin/spyking-circus-subtask", line 11, in <module>
    sys.exit(main())
  File "/home/tyler/lib/anaconda3/lib/python3.6/site-packages/circus/scripts/subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/home/tyler/lib/anaconda3/lib/python3.6/site-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/home/tyler/lib/anaconda3/lib/python3.6/site-packages/circus/filtering.py", line 280, in main
    data_file_out.allocate(shape=data_file_in.shape)
  File "/home/tyler/lib/anaconda3/lib/python3.6/site-packages/circus/files/raw_binary.py", line 31, in allocate
    self.data = numpy.memmap(self.file_name, offset=self.data_offset, dtype=data_dtype, mode='w+', shape=shape)
  File "/home/tyler/lib/anaconda3/lib/python3.6/site-packages/numpy/core/memmap.py", line 267, in __new__
    offset=array_offset, order=order)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

```

**Comment by yger** [comment]
Dear Tyler

As I'm not using the BRW file format, any small file would be welcome to
debug. I'll have a look next Monday if I have one, could be the case. From
what I can read in the error, are you filtering on site or not? Did you
used default params (and thus filtered on site) or are you trying to not
overwrite the original file? Can you send me the .params ?

Best

Pierre

**Comment by yger** [comment]
Any update on this issue? I can not reproduce it here, so please tell me: if this is also the case when overwrite is set to False, or please send me a small BRW file such that I can test. I guess this is a python3.6 casting issue

**Comment by tbenst** [comment]
Hi Pierre, I haven't gotten a smaller file yet, but uploaded an example to AWS:

https://s3-us-west-2.amazonaws.com/open-science/public/sample_recordng.brw (160GB)

Let me know if this is unwieldy and I will upload a new file in the next couple days when I get a shorter recording. Also, I expect that this recording has some saturation issues so may present difficulties for the sorting algorithm but hopefully is sufficient for debugging the read-in!

**Comment by tbenst** [comment]
Quick update: have a smaller 5GB file that should be more manageable: https://s3-us-west-2.amazonaws.com/open-science/public/example.brw -- I deleted the other 160GB file.

Yes, this error occurs when overwrite is set to False

**Comment by yger** [comment]
Thanks a lot for the smaller file, I'll have a look ! Because with some
dummy BRW file that I had here (7s of data only) I wasn't able to reproduce
the error. I'll try with Python 3.xx, as it may be the source of the
problem.

Best

Pierre

2017-12-22 1:01 GMT+01:00 tbenst <notifications@github.com>:

**Comment by yger** [comment]
This has been fixed, it was a Python3 error

**Comment by tbenst** [comment]
Hi @yger, unfortunately not fully resolved. I'm now running under Python2.7 as it sounds like this is tested more.

```
Traceback (most recent call last):
  File "/home/tyler/lib/anaconda3/envs/python2/bin/spyking-circus-subtask", line 11, in <module>
    load_entry_point('spyking-circus==0.6.3', 'console_scripts', 'spyking-circus-subtask')()
  File "/home/tyler/lib/anaconda3/envs/python2/lib/python2.7/site-packages/spyking_circus-0.6.3-py2.7.egg/circus/scripts/subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/home/tyler/lib/anaconda3/envs/python2/lib/python2.7/site-packages/spyking_circus-0.6.3-py2.7.egg/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/home/tyler/lib/anaconda3/envs/python2/lib/python2.7/site-packages/spyking_circus-0.6.3-py2.7.egg/circus/filtering.py", line 308, in main
    filter_file(data_file_in, data_file_out, do_filter, remove_median)
  File "/home/tyler/lib/anaconda3/envs/python2/lib/python2.7/site-packages/spyking_circus-0.6.3-py2.7.egg/circus/filtering.py", line 83, in filter_file
    local_chunk[:, i] -= numpy.median(local_chunk[:, i]) 
IndexError: index 4096 is out of bounds for axis 1 with size 4096
```

**Comment by yger** [comment]
I'll see if I can reproduce this with the small datafile you gave me. This
error however does not really look like a python2/3 issue, but more like a
problem with number of detected channels in the datafiles

Best

Pierre

2018-01-13 23:10 GMT+01:00 tbenst <notifications@github.com>:

**Comment by tbenst** [comment]
Hey Pierre, got it working! Thanks for all your help.
Has been running for 33 hours on my local machine w/ 6 CPUs, with slow but steady progress, [full output so far](https://gist.github.com/tbenst/370af3e3a97e53f3a910f43d05b5cb6a). Not sure yet if it's going to work, let me know if you have any thoughts on parameters.

```
-------------------------  Informations  -------------------------
| Number of clusters found : 7616
| Number of local merges   : 4621
| Not enough spikes gathered: -put safety_space=False?
|                             -decrease smart_search?
| 2 electrodes has 10 clusters: -increase max_clusters?
|                               -increase sim_same_elec?
```

**Comment by yger** [comment]
Ok, cool. Tout be honest, for such a large dataset, 6 CPU are not enough so
you should not be in a hurry. You'll see how it goes, hopefully it will
work, but I would expect the code to take quite a while to run. Regarding
the parameters, if you want to reduce memory footprint, be sure that N_t is
set to 3 instead of 5 (depend on your spikes also), and since you have very
few spikes you can turn off the smart search. You can also play with the
radius and decrease the spatial extent of the templates (150-200um)

Let me know how everything goes.

Pierre

**Comment by tbenst** [comment]
Great, thanks for the tips!! I will try adjusting N_t to see if I can get
the memory down to 6GB per thread. If so, will try 30-120 CPUs on our HPC.
